name: nb-javac

on: [push]
#  push:
#    branches: [ master ]
jobs: 
  linux: 
    name: "nb-javac build and test"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: 23

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: 21

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: 17
        
      - name: Build on JDK 17
        run: ant -f make/langtools/netbeans/nb-javac jar

      - name: Test on JDK 17
        run: JAVA_HOME=$JAVA_HOME_17 ant -f make/langtools/netbeans/nb-javac test

      - name: Test on JDK 21
        run: JAVA_HOME=$JAVA_HOME_21 ant -f make/langtools/netbeans/nb-javac test

      - name: Test on JDK 23
        run: JAVA_HOME=$JAVA_HOME_23 ant -f make/langtools/netbeans/nb-javac test

      - name: Build patched JDK 17
        run: ./build-jdk.sh
