name: NetBeans Smoketest

on: [push]
#  push:
#    branches: [ master ]
jobs:
  linux:
    name: "NetBeans on nb-javac"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
            distribution: 'temurin'
            java-version: 25

      - name: Run Jackpot
        run: ant -f make/langtools/netbeans/nb-javac clean jackpot

      - name: Build
        run: ant -f make/langtools/netbeans/nb-javac jar

# build nb
      - name: Checkout NetBeans 23
        run: |
            git clone https://github.com/apache/netbeans
            cd netbeans
            git checkout 2985f1fa57ce0c1877bad0f86d5e5504d65f9286

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
            distribution: 'temurin'
            java-version: 17

      - name: Build NetBeans with latest nb-javac
        run: ant -f netbeans build -Dnbjavac.class.path=`pwd`/make/langtools/netbeans/nb-javac/dist/nb-javac-*.jar

# test nb
#      - name: Set up JDK 21
#        uses: actions/setup-java@v5
#        with:
#            distribution: 'temurin'
#            java-version: 21

      - name: Setup Xvfb
        run: |
          echo "DISPLAY=:99.0" >> $GITHUB_ENV
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Test with Commit Validation
        run: |
          NB_JAVAC=`pwd`/make/langtools/netbeans/nb-javac/dist/nb-javac-*.jar
          ant -f netbeans commit-validation -Dnbjavac.class.path=$NB_JAVAC

