name: NetBeans Smoketest

on: [push]
#  push:
#    branches: [ master ]
jobs:
  linux:
    name: "NetBeans on nb-javac"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: 17

      - name: Jackpot on JDK 17
        run: ant -f make/langtools/netbeans/nb-javac clean jackpot

      - name: Finish Build on JDK 17
        run: ant -f make/langtools/netbeans/nb-javac jar

      - name: Check NetBeans 23 out
        run: |
            git clone https://github.com/apache/netbeans
            cd netbeans
            git checkout 2985f1fa57ce0c1877bad0f86d5e5504d65f9286

      - name: Build NetBeans with latest nb-javac
        run: ant -f netbeans build -Dnbjavac.class.path=`pwd`/make/langtools/netbeans/nb-javac/dist/nb-javac-*.jar

      - name: Setup Xvfb
        run: |
          echo "DISPLAY=:99.0" >> $GITHUB_ENV
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Test with Commit Validation
        run: JAVA_HOME=`cat jdk11` ant -f netbeans commit-validation -Dnbjavac.class.path=`pwd`/make/langtools/netbeans/nb-javac/dist/nb-javac-*.jar
